### ISSUE TITLE
Lobby server is degrading performance over time and causes very slow login.

### ISSUE THREAD

**Issue by jensvdh** [worldofbalance/wob-server#47]

**Comment by dlhoff** [comment]
Please see the screen captures below. They illustrate some of the problems with the lobby code. 

In the 1st capture we see the client connecting to thecity on port 9270. On Jens' server it says 9255.

Then we see many duplicate protocols numbers. This may not be causing a problem, but i think we should clean this up. I understand that it is one of the mini-games reloading all of the protocols again. The multiplayer convergence game depends upon proper network communication a lot. Some of the duplicates are for convergence game. This might be causing a problem. So i think we should clean it up.

In the 2nd capture we see the client connecting on two other ports 9253, 9258 for 2 of the remote servers.

In the 3rd capture, it is repeatedly sending requests to login to the RR server. I'm not playing Running Rhino.

All these screen captures were taken during the same session. It was a session in which i could not login. I entered the username and password and clicked the button, but no client could login. The clients did nothing. They just stayed on the login screen. 

Then, the 4rd capture shows the server results. Notice is says that Aaron3, JuneJ and MikeM all successfully logged in.

Yet, the clients for those 3 players would not move past the login screen. I clicked the login button and nothing happened. After some time, i clicked the login buttons again. Still no response. The server says it successfully logged them in, but the client is frozen. Maybe this problem is related to the repeated attempts to log into the RR server. Why are we doing that? I think this problem is related to the login problems that we have discussed and is related to the convergence game problems.

Finally, the 5th capture shows repeated null references related to tile purchase in the lobby. These things are not good.

I think the multiplayer convergence failure yesterday is caused by problems in lobby/login and those problems potentially could effect other games and mess up our trial.

![e1](https://cloud.githubusercontent.com/assets/17733350/18496380/36d24426-79da-11e6-98d0-289b246f9d3d.PNG)

![e2](https://cloud.githubusercontent.com/assets/17733350/18496382/3df7138a-79da-11e6-8719-487895bd973c.PNG)

![e3](https://cloud.githubusercontent.com/assets/17733350/18496384/43840df8-79da-11e6-9cf6-512049822337.PNG)

![e4](https://cloud.githubusercontent.com/assets/17733350/18496388/4aff8a80-79da-11e6-92ae-d4148951bed1.PNG)

![e5](https://cloud.githubusercontent.com/assets/17733350/18496391/4ff6da02-79da-11e6-89e7-d59bebc5d64b.PNG)

**Comment by jensvdh** [comment]
Thanks!

**Comment by dlhoff** [comment]
I just played a game with the server running locally on my laptop and it works fine.
1. I can login without any problems.
2. No blue screen in the lobby. The tiles appear immediately once i enter the lobby.
3. I played a 2 person game and it went fast and without problems. Please see screen captures.

I wanted to clarify my statements concerning the server on the cvg account. 

I had problems the first time i used the server on cvg which i started yesterday (Tuesday, 9/13), but i have used it several times since without any problems.

![j1](https://cloud.githubusercontent.com/assets/17733350/18526910/5be5f1ca-7a77-11e6-82c1-6f9534d77a47.PNG)

![j2](https://cloud.githubusercontent.com/assets/17733350/18526921/66b9a66e-7a77-11e6-9e8f-e7aec646fba2.PNG)

**Comment by jensvdh** [comment]
OK, if we can eliminate with 100% certainty that the issue is not happening on the cvg_cvg account. You are sure on this? Since you also say you are not seeing the issue on localhost then that leaves only 2 possible angles:
- Somehow CPU access is restricted on a per account basis. so the wob_wob account is overloaded, causing slow performance However the initial login is fast, and then the errors starts rolling in, so I don't think this is the cause.
- The build process for the wob_wob creates a JAR file using the Command Line, perhaps something is wrong during the creation of the JAR file that causes the errors, to eliminate this possiblity I can create the JAR file using Travis/Command line and send it to you, then we can host that under the CVG account and see if we spot the issue there.
- Looks like all logs point to the Running Rhino server. We can take it down and try again? Eliminating the minigames one by one and re-enabling them until we spot the issue.

Any thoughts?
